server:
  port: 8086
spring:
  application:
    name: booking-service
  datasource:
    password: admin
    username: postgres
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:15432}/bankservice
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  kafka:
    consumer:
      group-id: response-from-bank
    bootstrap-servers: localhost:29092

messaging:
  topic:
    making-payment: topic-making-payment
    bank-payment: topic-bank-payment